apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: loki
    release: loki
  name: storage-loki-0
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: standard
  volumeMode: Filesystem
